.\" Copyright (c) 2007
.\"   Ademar de Souza Reis Jr. <ademar@ademar.org>
.\"   (based on sniffdet manpage)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.TH AMORAD 8 2007-11-11 "amorad manpage" "A Remote Mobile Assistant"
.SH NAME
amorad - Amora (A Remote Mobile Assistant) daemon
.SH SYNOPSIS
.PP
amorad [options]
.PP
.SH DESCRIPTION
.PP
Amora is an application that enables you to control your PC desktop using
a cellphone. It uses bluetooth to send mouse and keyboard events to the
graphical session. With it you can control your slides in OpenOffice.org,
movies or any other application. Amora also has a screenshot feature, where
you can see a thumbnail in the cellphone screen of the currently focused
window in your desktop.
.PP
The server (amorad) is written in C using Xlib and XTest to send events for
X session and the POSIX socket API for I/O. It must be started by the user,
inside a valid X session.
.SH OPTIONS
.TP
\fB-h\fR
Help (usage) message
.br
.TP
\fB-l\fR
Set a specific path for the log file
.br
.TP
\fB-v\fR
Show program version and exit
.br
.PP
.SH AMORA CLIENT
.PP
In order to use amora, you need a mobile phone with amora-client
installed and running. The current client is implemented in Python
for S60 (Nokia cellphones).
.SH BUGS
See the current bugs and open new ones in the project website.
.br
.PP
.SH CREDITS
Author:
Adenilson Cavalcanti da Silva
.PP
Contributions from: Ademar de Souza Reis Jr., Alexis Younes, Thiago Marcos
Santos, Wilson Prata and others;
.SH SEE ALSO
.BR http://code.google.com/p/amora/
